using AdventOfCode.Day1;
using AdventOfCode.Day10;
using AdventOfCode.Day11;
using AdventOfCode.Day12;
using AdventOfCode.Day13;
using AdventOfCode.Day14;
using AdventOfCode.Day15;
using AdventOfCode.Day16;
using AdventOfCode.Day17;
using AdventOfCode.Day18;
using AdventOfCode.Day19;
using AdventOfCode.Day2;
using AdventOfCode.Day20;
using AdventOfCode.Day3;
using AdventOfCode.Day4;
using AdventOfCode.Day5;
using AdventOfCode.Day6;
using AdventOfCode.Day7;
using AdventOfCode.Day8;
using AdventOfCode.Day9;

Day1.Go();
Day2.Go();
Day3.Go();
Day4.Go();
Day5.Go();
Day6.Go();
Day7.Go();
Day8.Go();
Day9.Go();
Day10.Go();
Day11.Go();
Day12.Go();
Day13.Go();
Day14.Go();
Day15.Go();
Day16.Go();
Day17.Go();
Day18.Go();
Day19.Go();
Day20.Go();

Console.Read();